apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-server
    spec:
      containers:
      - name: springboot-server
        image: registry.gitlab.com/t014/springboot_server
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com